//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.06 at 01:52:09 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.claude.com/actors-ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.claude.actors_ws;
